// /////////////////////////////////////////////////////////////////
// Generated by medPluginGenerator
// /////////////////////////////////////////////////////////////////


#include "undoRedoRegistration.h"
#include "undoRedoRegistrationToolBox.h"

#include <QtGui>

#include <dtkCore/dtkAbstractDataFactory.h>
#include <dtkCore/dtkAbstractData.h>
#include <dtkCore/dtkAbstractProcessFactory.h>
#include <dtkCore/dtkAbstractProcess.h>
#include <dtkCore/dtkAbstractViewFactory.h>
#include <dtkCore/dtkSmartPointer.h>

#include <medAbstractView.h>
#include <medAbstractDataImage.h>

#include <medToolBoxFactory.h>
#include <medRegistrationSelectorToolBox.h>
#include <registrationFactory/registrationFactory.h>


class undoRedoRegistrationToolBoxPrivate
{
public:
    QPushButton * undoButton;
    QPushButton * redoButton;
    QPushButton * resetButton;
    QListWidget * transformationStack;
    QIcon arrowCurrentStep; 
    int currentStep;
    dtkSmartPointer<undoRedoRegistration> m_UndoRedo;

    // Displacement Field Visualization
    QPushButton * saveButton;
    QPushButton * loadButton;
    QPushButton * warpButton;
    registrationFactory::WarpedImageType * warpedImage;
};

undoRedoRegistrationToolBox::undoRedoRegistrationToolBox(QWidget *parent) : medRegistrationAbstractToolBox(parent), d(new undoRedoRegistrationToolBoxPrivate)
{
    // Undo/redo Buttons
    d->undoButton = new QPushButton(QIcon(":undoRedoRegistration/icons/ArrowDown.png"),tr("Undo"),this);
    d->redoButton = new QPushButton(QIcon(":undoRedoRegistration/icons/ArrowUp.png"),tr("Redo"),this);
    d->undoButton->setEnabled(false);
    d->redoButton->setEnabled(false);
    d->resetButton = new QPushButton(tr("Reset"),this);
    d->resetButton->setEnabled(false);

    connect(d->undoButton,SIGNAL(clicked()),this,SLOT(onUndo()));
    connect(d->redoButton,SIGNAL(clicked()),this,SLOT(onRedo()));
    connect(d->resetButton,SIGNAL(clicked()),registrationFactory::instance(),SLOT(reset()));

    d->arrowCurrentStep = QIcon(":undoRedoRegistration/icons/BlueArrowRight.png");
    d->currentStep = -1;

    d->m_UndoRedo = new undoRedoRegistration();
    // Transformation Stack
    d->transformationStack = new QListWidget(this);

    QVBoxLayout *layoutButtonUndoRedo = new QVBoxLayout;
    layoutButtonUndoRedo->addWidget(d->redoButton);
    layoutButtonUndoRedo->addWidget(d->undoButton);
    layoutButtonUndoRedo->addWidget(d->resetButton);
    QHBoxLayout *layoutButtonsStack = new QHBoxLayout;
    layoutButtonsStack->addLayout(layoutButtonUndoRedo);
    layoutButtonsStack->addWidget(d->transformationStack);
    d->transformationStack->setFixedSize(180,160);

    

    this->setTitle(tr("Stack of transformations"));
    connect(registrationFactory::instance(),SIGNAL(transformationAdded(int,QStringList*)),this,SLOT(addTransformationIntoList(int, QStringList*)));
    connect(registrationFactory::instance(),SIGNAL(transformationStackReset()),this,SLOT(onTransformationStackReset()));


    //Displacement Visualization 
    d->saveButton = new QPushButton(QPixmap("E:/Medinria-OldCode/Modules/ImageFusion/pixmaps/fieldsave.xpm"),tr("Save"),this);
    d->loadButton = new QPushButton(QPixmap("E:/Medinria-OldCode/Modules/ImageFusion/pixmaps/fieldopen.xpm"),tr("Load"),this);
    d->warpButton = new QPushButton(QPixmap("E:/Medinria-OldCode/Modules/ImageFusion/pixmaps/fieldupdate.xpm"),tr("Warp"),this);
    d->warpButton->setToolTip("Display a grid warped according to the current transformation");
    d->saveButton->setToolTip("Save the displacement (vector) field to a file");
    d->loadButton->setToolTip("Load a displacement (vector) field");
    d->saveButton->setMinimumHeight(45);
    d->saveButton->setIconSize(QSize(40,40));
    d->loadButton->setMinimumHeight(45);
    d->loadButton->setIconSize(QSize(40,40));
    d->warpButton->setMinimumHeight(45);
    d->warpButton->setIconSize(QSize(40,40));
    d->warpButton->setEnabled(true);
    d->saveButton->setEnabled(false);

    connect(d->saveButton,SIGNAL(clicked()),this,SLOT(save()));
    connect(d->loadButton,SIGNAL(clicked()),this,SLOT(load()));
    connect(d->warpButton,SIGNAL(clicked()),SLOT(warpGrid()));

    QHBoxLayout *layoutButtonWarp = new QHBoxLayout;
    layoutButtonWarp->addWidget(d->loadButton);
    layoutButtonWarp->addWidget(d->saveButton);
    layoutButtonWarp->addWidget(d->warpButton);
    QVBoxLayout *wholeLayout = new QVBoxLayout;
    wholeLayout->addLayout(layoutButtonsStack);
    wholeLayout->addLayout(layoutButtonWarp);

    QWidget * layoutSection = new QWidget(this);
    layoutSection->setLayout(wholeLayout);

    addWidget(layoutSection);
}

undoRedoRegistrationToolBox::~undoRedoRegistrationToolBox(void)
{
    delete d;

    d = NULL;
}

bool undoRedoRegistrationToolBox::registered(void)
{
    return medToolBoxFactory::instance()-> registerToolBox<undoRedoRegistrationToolBox>
        ("undoRedoRegistrationToolBox", 
        tr("undoRedoRegistration"), 
        tr("short tooltip description"), 
        QStringList() << "UndoRedoRegistration");
}

void undoRedoRegistrationToolBox::onUndo()
{
    if(!this->parentToolBox())
        return;

    if ((d->currentStep >= 0) && (d->currentStep < d->transformationStack->count()))
    {
        updatePositionArrow(d->currentStep+1);
        d->m_UndoRedo->undo();
        this->parentToolBox()->handleOutput(medRegistrationSelectorToolBox::undo);
        d->redoButton->setEnabled(true);
    }

    if (d->currentStep>=d->transformationStack->count()){
        d->undoButton->setEnabled(false);
        d->resetButton->setEnabled(false);
    }
}

void undoRedoRegistrationToolBox::onRedo()
{
    if(!this->parentToolBox())
        return;
    if (d->currentStep>0)
    {
        updatePositionArrow(d->currentStep-1);
        d->m_UndoRedo->redo();
        this->parentToolBox()->handleOutput(medRegistrationSelectorToolBox::redo,d->transformationStack->item(d->currentStep)->text().remove(" "));
        d->undoButton->setEnabled(true);
        d->resetButton->setEnabled(true);
    }

    if (d->currentStep<=0)
        d->redoButton->setEnabled(false);
}

void undoRedoRegistrationToolBox::onTransformationStackReset(void)
{
    d->currentStep=-1;
    while (d->transformationStack->count()!=0)
    {
        QListWidgetItem * tmp = d->transformationStack->takeItem(0);    
        delete tmp;
    }
    d->undoButton->setEnabled(false);
    d->redoButton->setEnabled(false);
    d->resetButton->setEnabled(false);
    
    registrationFactory::instance()->getItkRegistrationFactory()->Modified();
    d->m_UndoRedo->generateOutput();
    this->parentToolBox()->handleOutput(medRegistrationSelectorToolBox::reset);
}

void undoRedoRegistrationToolBox::addTransformationIntoList(int i, QStringList * methodParameters){
    if (i!=-1){
        QString buffer = "";
        if (methodParameters)
        {
            buffer = methodParameters->at(0);
            for(int k = 1;k<methodParameters->size();k++)
                buffer = buffer + QString("\n") + methodParameters->at(k);
        }
        if ((d->currentStep >= 0) && (d->currentStep < d->transformationStack->count()))
            d->transformationStack->item(d->currentStep)->setIcon(QIcon());
        for(int k = d->currentStep-1;k>=0;k--)
        {
            QListWidgetItem * tmp = d->transformationStack->takeItem(k);
            delete tmp;
        }  
        d->currentStep = 0;

        d->transformationStack->insertItem(d->currentStep,QString::number(d->transformationStack->count()+1)+ ". " + this->parentToolBox()->getNameOfCurrentAlgorithm().remove(" ")); 
        d->transformationStack->item(d->currentStep)->setToolTip(buffer);
        d->transformationStack->item(d->currentStep)->setIcon(d->arrowCurrentStep);
        d->transformationStack->item(d->currentStep)->setForeground(QColor(0,200,0));
    }
    d->undoButton->setEnabled(true);
    d->resetButton->setEnabled(true);
    d->redoButton->setEnabled(false);
}

void undoRedoRegistrationToolBox::updatePositionArrow(int newStep){

    if ((d->transformationStack->count() != 0) && (newStep >= 0))
    {
        if (!(d->transformationStack->count()==d->currentStep)){
            d->transformationStack->item(d->currentStep)->setIcon(QIcon());
        }
        d->currentStep = newStep;
        if (!(d->transformationStack->count()==d->currentStep)){
            d->transformationStack->item(d->currentStep)->setIcon(d->arrowCurrentStep);
            d->transformationStack->item(d->currentStep)->setForeground(QColor(0,200,0));
        }
    }
    for(int k = d->currentStep-1;k>=0;k--){
        d->transformationStack->item(k)->setForeground(QColor(255,255,255));
    }
}

void undoRedoRegistrationToolBox::setRegistrationToolBox(medRegistrationSelectorToolBox *toolbox){
    medRegistrationAbstractToolBox::setRegistrationToolBox(toolbox);
    toolbox->setUndoRedoProcess(d->m_UndoRedo);
    connect(this->parentToolBox(),SIGNAL(success()),this,SLOT(onRegistrationSuccess()));
}

void undoRedoRegistrationToolBox::onRegistrationSuccess(){
    registrationFactory::instance()->addTransformation(static_cast<itkProcessRegistration*>(this->parentToolBox()->process())->getTransform(),static_cast<itkProcessRegistration*>(this->parentToolBox()->process())->getTitleAndParameters());
    registrationFactory::instance()->getItkRegistrationFactory()->Modified();
    d->m_UndoRedo->generateOutput(true,this->parentToolBox()->process());
    this->parentToolBox()->handleOutput();
}

void undoRedoRegistrationToolBox::load()
{

}

void undoRedoRegistrationToolBox::save()
{

}

void undoRedoRegistrationToolBox::warpGrid()
{
    itk::ImageBase<3>::Pointer result = registrationFactory::instance()->getItkRegistrationFactory()->ExportWarpedImage();
    dtkSmartPointer<dtkAbstractData> output =  dtkAbstractDataFactory::instance()->create ("itkDataImageUChar3");

    if (result)
    {
        output->setData(result);
        this->parentToolBox()->visualizeDisplacementField(output);
    }
}