// /////////////////////////////////////////////////////////////////
// Generated by medPluginGenerator
// /////////////////////////////////////////////////////////////////

#include "displacementFieldVisualization.h"
#include "displacementFieldVisualizationPlugin.h"
#include "displacementFieldVisualizationToolBox.h"

#include <dtkLog/dtkLog.h>

// /////////////////////////////////////////////////////////////////
// displacementFieldVisualizationPluginPrivate
// /////////////////////////////////////////////////////////////////

class displacementFieldVisualizationPluginPrivate
{
public:
    // Class variables go here.
    static const char *s_Name;
};

const char * displacementFieldVisualizationPluginPrivate::s_Name = "displacementFieldVisualization";

// /////////////////////////////////////////////////////////////////
// displacementFieldVisualizationPlugin
// /////////////////////////////////////////////////////////////////

displacementFieldVisualizationPlugin::displacementFieldVisualizationPlugin(QObject *parent) : dtkPlugin(parent), d(new displacementFieldVisualizationPluginPrivate)
{
    
}

displacementFieldVisualizationPlugin::~displacementFieldVisualizationPlugin()
{
    delete d;
    
    d = NULL;
}

bool displacementFieldVisualizationPlugin::initialize()
{
    if(!displacementFieldVisualization::registered())
        dtkWarn() << "Unable to register displacementFieldVisualization type";
    
    if(!displacementFieldVisualizationToolBox::registered())
        dtkWarn() << "Unable to register displacementFieldVisualization toolbox";
    
    return true;
}

bool displacementFieldVisualizationPlugin::uninitialize()
{
    return true;
}

QString displacementFieldVisualizationPlugin::name() const
{
    return "displacementFieldVisualizationPlugin";
}

QString displacementFieldVisualizationPlugin::description() const
{
    return tr("");
}

QString displacementFieldVisualizationPlugin::version() const
{
    return DISPLACEMENTFIELDVISUALIZATIONPLUGIN_VERSION;
}

QString displacementFieldVisualizationPlugin::contact() const
{
    return "";
}

QStringList displacementFieldVisualizationPlugin::authors() const
{
    QStringList list;
    return list;
}

QStringList displacementFieldVisualizationPlugin::contributors() const
{
    QStringList list;
    return list;
}

QString displacementFieldVisualizationPlugin::identifier() const
{
    return displacementFieldVisualizationPluginPrivate::s_Name;
}


QStringList displacementFieldVisualizationPlugin::tags() const
{
    return QStringList();
}

QStringList displacementFieldVisualizationPlugin::types() const
{
    return QStringList() << "displacementFieldVisualization";
}
QStringList displacementFieldVisualizationPlugin::dependencies() const
{
    return QStringList();
}

Q_EXPORT_PLUGIN2(displacementFieldVisualizationPlugin, displacementFieldVisualizationPlugin)
