// /////////////////////////////////////////////////////////////////
// Generated by medPluginGenerator
// /////////////////////////////////////////////////////////////////

#include "displacementFieldVisualization.h"

#include <dtkCore/dtkAbstractData.h>
#include <dtkCore/dtkAbstractDataFactory.h>
#include <dtkCore/dtkAbstractProcessFactory.h>

// /////////////////////////////////////////////////////////////////
//
// /////////////////////////////////////////////////////////////////




// /////////////////////////////////////////////////////////////////
// displacementFieldVisualizationPrivate
// /////////////////////////////////////////////////////////////////

class displacementFieldVisualizationPrivate
{
public:
};

// /////////////////////////////////////////////////////////////////
// displacementFieldVisualization
// /////////////////////////////////////////////////////////////////

displacementFieldVisualization::displacementFieldVisualization() : itkProcessRegistration(), d(new displacementFieldVisualizationPrivate)
{

}

displacementFieldVisualization::~displacementFieldVisualization()
{
    delete d;
    d = 0;
}

bool displacementFieldVisualization::registered()
{
    return dtkAbstractProcessFactory::instance()->registerProcessType("displacementFieldVisualization",
                                                                 createDisplacementFieldVisualization);
}

QString displacementFieldVisualization::description() const
{
    return "displacementFieldVisualization";
}



// /////////////////////////////////////////////////////////////////
// Templated Version of update
// /////////////////////////////////////////////////////////////////


int displacementFieldVisualization::update(itkProcessRegistration::ImageType imgType)
{return 0;}

bool displacementFieldVisualization::writeTransform(const QString& file)
{return false;}

// /////////////////////////////////////////////////////////////////
// Type instanciation
// /////////////////////////////////////////////////////////////////

dtkAbstractProcess *createDisplacementFieldVisualization()
{
    return new displacementFieldVisualization;
}
