// /////////////////////////////////////////////////////////////////
// Generated by medPluginGenerator
// /////////////////////////////////////////////////////////////////

#pragma once

#include <medRegistrationAbstractToolBox.h>
#include "displacementFieldVisualizationPluginExport.h"

class displacementFieldVisualizationToolBoxPrivate;

class DISPLACEMENTFIELDVISUALIZATIONPLUGIN_EXPORT displacementFieldVisualizationToolBox : public medRegistrationAbstractToolBox
{
    Q_OBJECT
    
public:
    displacementFieldVisualizationToolBox(QWidget *parent = 0);
    ~displacementFieldVisualizationToolBox();
    
public:
    static bool registered();
    
public slots:
    void load();
    void save();
    void warpGrid();
    
private:
    displacementFieldVisualizationToolBoxPrivate *d;
};


