// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#pragma once

#ifdef WIN32
    #ifdef displacementFieldVisualizationPlugin_EXPORTS
        #define DISPLACEMENTFIELDVISUALIZATIONPLUGIN_EXPORT __declspec(dllexport) 
    #else
        #define DISPLACEMENTFIELDVISUALIZATIONPLUGIN_EXPORT __declspec(dllimport) 
    #endif
#else
    #define DISPLACEMENTFIELDVISUALIZATIONPLUGIN_EXPORT
#endif


